# Generated by Django 4.2.1 on 2023-06-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
