# Generated by Django 4.2.1 on 2023-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('app-web-development', 'App & Web Development'), ('digital-marketing', 'Digital Marketing'), ('graphics-designing', 'Graphics Designing'), ('python-programming', 'Python Programming'), ('artificial-intelligence', 'Artificial Intelligence'), ('government-exams', 'Government Exams')], default='app-web-development', max_length=100),
        ),
    ]
